### ISSUE TITLE
[Bug] Move issue templates and PR template config out of workflows directory

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger-website#10]
The issue templates and PR template files are now under the `.github/workflows` directory which will not take effect to this repo, should move them to `.github` directory instead.

**Comment by Neilblaze** [comment]
Ah yes, I just noticed that. I had my CI logger set on local that's why it was set under `.github/workflows`, so technically **yes!**, we should shift them to one level up, into `.github` directory.

@frank-zsy Should I go ahead and open a PR for this?

**Comment by frank-zsy** [comment]
Of course, you can pick up any issue you like and I can do these too, just feel free to fix these issues as you like.
