### ISSUE TITLE
[OSPP] Task:Building and improving user documentation and developer guides

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger-website#24]
This issue is for tracking the task of OSPP: Building and improving user documentation and developer guides

The Opendigger repository has implemented many data insight metrics, and has also introduced some data insight metrics from the CHAOSS community. Now, it is necessary to improve the interpretability of these metrics and ultimately complete the documentation of the user guide and developer manual for the Opendigger official website built on the Docusaurus framework.

Specific examples have been mentioned in the issue: #11

So to implement this task, the developer should:
1. Design and implement a solution to enhance the interpretability of metrics.
2. Complete the documentation for metric data introduction.
3. Complete the writing of the developer guide, database table structure, metric development, and scheduled tasks introduction documents in the developer documentation. (Each item has a corresponding title in the Chinese document on the open-digger-website. )

**Comment by Neilblaze** [comment]
Hi @Peng99999, thanks for jotting down the objectives. I'm excited to get started. So far I have had a discussion with @frank-zsy regarding the potential tasks, and now the tasks look more streamlined. Also, I'll need to communicate with you before taking up actionable items, so can I ping you over on [Slack](https://join.slack.com/t/opendigger/shared_invite/zt-2lxx3oys1-FRQhblKqxYlEP_bYrlq3fg)? Thanks again ^_^

**Comment by Peng99999** [comment]
I see that you, Frank, and I are in a Slack chat group. I’d be happy to communicate with you here or on Slack.

**Comment by Neilblaze** [comment]
@Peng99999 Sure thing, thanks! 😄

**Comment by Neilblaze** [comment]
@Peng99999 please take a look at [this](https://opendigger.slack.com/archives/C076PCS77GQ/p1719841488509509) :)

**Comment by Peng99999** [comment]
I express my most sincere apologies for not replying to your message in time.  @Neilblaze (https://opendigger.slack.com/archives/C076PCS77GQ/p1719930249855619)

**Comment by Neilblaze** [comment]
All good! I'm on it 😄

**Comment by frank-zsy** [comment]
Finished by #25 , #28 , #31 , #45 .

Thanks to @Neilblaze , amazing work, so good in details.
