### ISSUE TITLE
Does the repository that the website is directed to need improvement?

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger-website#46]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

<img alt="image" width="300" src="https://github.com/user-attachments/assets/81736192-70f1-4630-ad21-7b7594512522">

Clicking on this icon on the website will redirect to the repository of Opendigger instead of  opendigger-website. 

There is a common scenario：👉 someone is browsing this website and then wants to check out the code of the website's repository, or they want to contribute to the website. So, they click the GitHub icon in the upper-right corner, but it redirects them to the Opendigger repository. Could this be misleading?

Should we add a link to redirect to the repository of opendigger-website?

**Comment by frank-zsy** [comment]
It is a good question, I think we can add a link to this repository in the footer part. The logo in the banner should point to OpenDigger repo.

**Comment by Neilblaze** [comment]
yes, +1 binding to @frank-zsy's suggestion!
