### ISSUE TITLE
[Doc] How to properly embed an SVG image into markdown doc

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger-website#52]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In the doc file https://open-digger.cn/docs/user_docs/metrics/global_openrank right now I use absolute URL for the embedded SVG image because a relative URL will fail to load and show a 404 page in the embed position.

But in the former version, I use `/img/global_openrank.svg` as `src` and all looks good in `npm start` and `npm run build && npm run serve`. But only after deployed, the image fails to load.

Besides the bug in production mode, it is also wrong in preview mode, because if I use `/img/global_openrank.svg`, I need to inject the base URL like `/pull_51/img/global_openrank.svg` to make it work.

I do not know how to make this work for all circumstances since it seems that `@site` does not work here.

Does anyone can help with this?

**Comment by frank-zsy** [comment]
@Neilblaze could you please give a look on this one and see if you know what happened here

**Comment by Neilblaze** [comment]
@frank-zsy sorry for the delay, I'm travelling right now and will be back by the 4th instant. I'll give it a closer look once I'm back, and hopefully come up with a solution. Thanks!

**Comment by Neilblaze** [comment]
This seemed like a Docusaurus glitch, but now it's fixed! Please take a reply, and reopen this issue if required.
cc: @frank-zsy

**Comment by frank-zsy** [comment]
Looks great, thanks for the help~
