### ISSUE TITLE
Query regarding Building and improving user documentation and developer guides 📜

### ISSUE THREAD

**Issue by Neilblaze** [X-lab2017/open-digger-website#7]
Hi @frank-zsy, I'm redirecting from [here](https://summer-ospp.ac.cn/org/prodetail/245520513), and I'm interested to know more about the project — "_Building and improving user documentation and developer guides_" , and so, how can I get started?

> I'm pretty familiar with the required tech stack & I have a ton of experience with Docusaurus, as well as React, Markdown & all of the required technologies. I've built my own blog page and I maintain it by frequently writing blogs which can be explored [here](https://blog.neilblaze.live). 

I can see that my potential mentor (listed) is **彭佳恒** (Peng Jiaheng), and have provided an email — [531055665@qq.com](mailto:531055665@qq.com). So, should I draft an email and drop it? And also, *is there any communication channel* that I can join to stay updated? 

Thanks!

**Comment by Peng99999** [comment]
Hi, welcome to contribute to the repository. 
If you have any questions, you can directly open an issue in this repository.

The homepage of opendigger provides an introduction to the existing metric documentation: https://github.com/X-lab2017/open-digger

**Comment by Peng99999** [comment]
This document explains how to use the sample data: https://github.com/X-lab2017/open-digger/blob/master/sample_data/README.md

Get start: https://github.com/X-lab2017/open-digger/blob/master/python_v2/README.md
And use opendigger to do some analysis work: https://github.com/X-lab2017/open-digger/blob/master/notebook/handbook.ipynb

**Comment by Neilblaze** [comment]
Thanks @Peng99999 for the info! Also, are there any slack or discord server where I can tap into to get more insights on the tasks that are up for grabs regarding "_[Building and improving user documentation and developer guides](https://summer-ospp.ac.cn/org/prodetail/245520513)_"?

I'll invest time in exploring the project further but yeah, a few good starter tasks can help me to get started.

**Comment by Peng99999** [comment]
Currently, there are none. If you have any questions or wish to communicate, please discuss in the issues of this repository (or opendigger: https://github.com/X-lab2017/open-digger). We usually discuss matters in the GitHub issues. @Neilblaze

**Comment by frank-zsy** [comment]
@Neilblaze Welcome, actually we do have a wechat group but no slack or discord channel available right now. But as more global developers starts to join us, I just start a slack channel, welcome to join us.

https://join.slack.com/t/slack-ok66537/shared_invite/zt-2ie5r42gz-q4dcm7FqDamZCYCkowgzyg

@Peng99999 We should start a new issue about the task which describes the details of the task to help developers get start.

**Comment by Neilblaze** [comment]
Thank you @frank-zsy for the invite! Now as soon as new tasks are set up by either or both of you and @Peng99999, I'll take that up! As of now, I'm trying to go through the resources provided by Peng to get a holistic idea of the codebase.
